xl : 3000 # 水路長(m)
nx: 31  # x方向格子数
j_channel: 1 # 水路の状態　1=一定勾配 2=勾配変化点あり
# j_channel=1の場合
slope: 0.001 # 全体の勾配
# j_channel=2の場合
x_slope : 100 # 勾配変化点
slope1 : 0.001 # 上流側勾配
slope2 : 0.01 # 下流側勾配
xb1 : 1000 # 突起始り地点の上流端からの距離（m)
xb2 : 1500 # 突起頂点の上流端からの距離(m)
xb3 : 2000 # 突起終了地点の上流からの距離(m)
dbed : 0.8 #突起高さ(m)
xw1 : 500 # 川幅変化点1の位置(m)
xw2 : 1000 # 川幅変化点2の位置(m)
xw3 : 1500 # 川幅変化点3の位置(m)
w0: 100 # 川幅1(m)(上流端)
w1: 100 # 川幅2(m)
w2: 100 # 川幅3(m)
w3: 100 # 川幅4(m)
w4: 100 # 川幅5(m)(下流端)
qp : 1000 #流量(m**3/2)
g : 9.8 #重力加速度
snm : 0.02 # 粗度係数
alh : 0.7 # 水位計算緩和係数
lmax : 50 # 水位計算最大繰り返し回数
errmax : 0.001 # 打ち切り誤差
hmin : 0.001 # 最小水深(m)
j_upstm : 2 # 上流端の条件 1=Wall, 2=Free, 3=Fixed Value
j_dwstm : 3 # 下流端の条件
alpha_up: 1.0 # 上流端の水深(等流水深に対する割合)
alpha_dw: 1.0 # 下流端の水深(等流水深に対する割合)

etime : 2400 # 計算終了時間(sec)
dt : 1 # 計算タイムステップ
tuk : 20 # アウトプットインターバル

diam: 0.005 # 河床材料の粒径(m)
lam: 0.4 # 空隙率
sub: 1.65 # 河床材料の水中比重
tsc: 0.05 # 無次元限界掃流力

alpha_up_sed: 1.0 #上流端の流砂（平衡流砂量に対する割合)

